language: java
jdk:
  - oraclejdk8
before_install:
  - sudo apt-get update
  - echo "Let's start Maven Package!"
  - mvn clean package
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag partner-factory:latest tobiashcrz/partner-factory:latest;
    docker push tobiashcrz/partner-factory;
  on:
    branch: master
notifications:
  email: false