version: '3.4'
services:
  partner-factory:
    image: partner-factory
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    networks:
      - udemy-network
networks:
    udemy-network:
      driver: bridge